 CREATE TABLE "SCOTT"."MEMBER" 
   (	"ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"PASSWD" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"DATE_NUMBER" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(25 BYTE), 
	"TEL" VARCHAR2(13 BYTE), 
	"NAME" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"REG_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID"));
     
     
  CREATE TABLE "SCOTT"."BOARDE" 
   (	"NUM" NUMBER(20,0) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"SUBJECT" VARCHAR2(75 BYTE) NOT NULL ENABLE, 
	"PASSWD" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"REG_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"READCOUNT" NUMBER DEFAULT 0, 
	"REF" NUMBER(20,0) NOT NULL ENABLE, 
	"RE_STEP" NUMBER(10,0) NOT NULL ENABLE, 
	"RE_LEVEL" NUMBER(10,0) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"IP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(500 BYTE), 
	 PRIMARY KEY ("NUM"));
     
alter table boarde 
add constraint fk_writer foreign key (writer) references login(id);

     